### ISSUE TITLE
Can't resolve 'dgram'

### ISSUE THREAD

**Issue by DaiganIT** [raweceek-temeletry/f1-2021-udp#37]
Hi, I have an empty react with typescript app
after doing the import and creating the client I get the error

Module not found: Error: Can't resolve 'dgram' in 'D:\**\node_modules\f1-2021-udp\build\src'

**Comment by DaiganIT** [comment]
doesn't run on web

**Comment by PrimeGoose** [comment]
does not run on web, because  dgram is not available in the browser, and that is not the only thing missing. 

You can run it in an Electron app it will work no problem, or on a nodejs server.
